---
- hosts: target 
  become: true
  become_user: root
  any_errors_fatal: true
  roles:
    - preconfig
    - docker-container-up
- hosts: all
  become: true
  become_user: root
  any_errors_fatal: true
  roles:
    - postconfig
