---
- name: Add sysadmins
  hosts: webservers
  any_errors_fatal: true
  tasks:
    - name: Add users block
      block:
        - name: Add "{{ user1_name }}" user
          user:
            name: "{{ user1_name }}"
            state: present
            create_home: true
            groups: 'sudo'
            shell: /bin/bash
            password: "{{ user1_passwd | password_hash('sha512') }}"
            generate_ssh_key: yes
            ssh_key_bits: 2048
            ssh_key_file: .ssh/id_rsa
        - name: Add "{{ user2_name }}" user
          user:
            name: "{{ user2_name }}"
            state: present
            create_home: true
            groups: 'sudo'
            shell: /bin/bash
            password: "{{ user2_passwd | password_hash('sha512') }}"
            generate_ssh_key: yes
            ssh_key_bits: 2048
            ssh_key_file: .ssh/id_rsa
        - name: Add SSH key for "{{ user1_name }}"
          ansible.posix.authorized_key:
            user: "{{ user1_name }}"
            state: present
            key: "{{ lookup('file', './keys/user1.id_rsa.pub') }}"
        - name: Add SSH key for "{{ user2_name }}"
          ansible.posix.authorized_key:
            user: "{{ user2_name }}"
            state: present
            key: "{{ lookup('file', './keys/user2.id_rsa.pub') }}"
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true
