#!/bin/bash
echo "Вводи логин, типа ivanov_i"
read username;
azpassword=$(echo "$username" | cut -c 1-3)123
password=$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 8 ; echo)
email_password=$(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 12 ; echo)
if [[ $username =~ ^[a-z]*_[a-z]$ ]]; then
    echo "DC login: $username"
    echo "DC password: $password"
    echo "Email: $username@ecepu.ru"
    echo "Email password: $email_password"
    echo "Azimut login: $username"
    echo "Azimut pass: $azpassword"
else
    echo "Введен некорректный юзернейм, он должен быть типа ivanov_i"
fi

